set(__QT_DEPLOY_TARGET_algorithmviz_core_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/libalgorithmviz_core.a)
set(__QT_DEPLOY_TARGET_algorithmviz_core_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_AlgorithmViz_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/AlgorithmViz)
set(__QT_DEPLOY_TARGET_AlgorithmViz_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_connector_test_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/connector_test)
set(__QT_DEPLOY_TARGET_connector_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_layout_engine_test_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/layout_engine_test)
set(__QT_DEPLOY_TARGET_layout_engine_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_undo_commands_test_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/undo_commands_test)
set(__QT_DEPLOY_TARGET_undo_commands_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_parser_serializer_test_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/parser_serializer_test)
set(__QT_DEPLOY_TARGET_parser_serializer_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_html_editor_ui_test_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/html_editor_ui_test)
set(__QT_DEPLOY_TARGET_html_editor_ui_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_shape_explorer_test_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/shape_explorer_test)
set(__QT_DEPLOY_TARGET_shape_explorer_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_main_window_integration_test_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/main_window_integration_test)
set(__QT_DEPLOY_TARGET_main_window_integration_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_svg_exporter_test_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/svg_exporter_test)
set(__QT_DEPLOY_TARGET_svg_exporter_test_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_html_editor_demo_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/html_editor_demo)
set(__QT_DEPLOY_TARGET_html_editor_demo_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_toolbar_demo_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/toolbar_demo)
set(__QT_DEPLOY_TARGET_toolbar_demo_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_canvas_property_demo_FILE /Users/liuchip/Workspace/Project C & C++/AlgorithmViz/build-release/canvas_property_demo)
set(__QT_DEPLOY_TARGET_canvas_property_demo_TYPE EXECUTABLE)
